### PR TITLE
Revert "fitlers out _NET_WM_WINDOW_TYPE_POPUP_MENU"

### LINKED ISSUE #64: Some apps minimized to panel tray still visible as "shadow" state
Discussions from #57, #59

Apps e.g. xwininfo, stacer app, jdownloader, fdm, when minimized to xfce panel, would still be visible under skippy-xd

image

image

### PR DESCRIPTION
**Pull request by felixfung**
This reverts commit 34d94967c019d774eedfe0586f789646698f17c4.

Closes #64

### CODE REVIEW

**Comment by ahmeteid7** [comment]
i tried it,
1-it successes in :zorin-menu will not appear under skippy-xd.

2-but doesn't succuss in: Single click to select window (as opposed to double-clicking,i don't know the reason, but i think it not will be problem, that happen only with one item(zorin menu) and only when use hot-corner with Zorin menu,

i noticed also that skippy-xd not be  considered as displaying on full-screen, if it was that, the hot-corner tools will ignore it,becuse these tools has option to disable the work of corners when there is app or game work on Fullscreen
Peek 2024-03-20 04-55
notice : what happen when i go to bottom-right-corner which it should show desktop, and should it not work in full-screen,but skippy not be considered as full-screen app

**Comment by felixfung** [comment]
So to summarize, either `clientList = _NET_CLIENT_LIST` or _NET_WM_WINDOW_TYPE_POPUP_MENU PR (which this PR reverts) successfully filters away zorin-menu, but neither fixes the double click issue, which most probably comes is because the first cause is to focus on skippy-xd, and the second to actually select window. Is that correct?

**Comment by ahmeteid7** [comment]
yes both success in filters away zorin-menu, so i think no need to _NET_WM_WINDOW_TYPE_POPUP_MENU.

for the new problems, they are two new problems:
1-skippy-xd not be considered full-screen app, so hot-corner still work when skippy show the windows, the hot-corner must be disabled when skippy preview the windows,because as u can see in the picture, when go to bottom-right corner, i get bug behavior, it make zoom to one of the window, or show strange things:

Peek 2024-03-20 14-49

2-the second problem that i have to double click to select the window, that happen in one case only(zorin-menu is popup and i'm using hot-corner)
i don't know may it related to the first problem , or may it that is the normal of zorin-menu and panel, that it must to click on the desktop to free the focus from it, because i tried xfcedashboard(alternative for skippy)and has the same thing, so my be that is the default and that is normal, but the first problem not normal and it not found in xfdashboard

**Comment by felixfung** [comment]
Skippy-xd is full screen app, but does not prevent other windows from taking focus away from skippy-xd window, which may result in weird behaviour/appearance, as you noted. If you maximize/resize apps during skippy-xd activation you get similar behaviour.

Arguably, skippy-xd should lock down on all of these: forbid these from happening. However these edge cases are rare, the user can actively avoid the scenarios, and ultimately does not affect user behaviour. On the other hand, in the unlikely case skippy-xd gets stuck due to bugs (which thankfully is rare nowadays), locking down on focus would threaten the user to kill the X session entirely.

Hence, I know about this issue long ago, but decide not to do anything about it. If you like, you can open a new issue to keep track of it, but probably I won't deal with it for long while.

For this PR, since _NET_WM_WINDOW_TYPE_POPUP_MENU windows should be filtered away in general, I will keep the following logic, and close without merging. Would you disagree?

**Comment by ahmeteid7** [comment]
ok, i agree with you.
for the feature of disabling hot-corner work during skippy preview, i will open separate issue to it.

**Pull request closed without merging**
