### PR TITLE
feat: add flake.nix

### PR DESCRIPTION
**Pull request by Lenivaya**
# Nix flake

Adds the ability to easily track and use the latest version of skippy-xd for NixOS users.

### CODE REVIEW

**Comment by felixfung** [comment]
Nice!

Can you please create on the root directory a "Packages" directory, then put in "DEBIAN" and "Nix" or "NixOS" as subdirectories?

**Comment by Lenivaya** [comment]
> Can you please create on the root directory a "Packages" directory, then put in "DEBIAN" and "Nix" or "NixOS" as subdirectories?

In terms of functionality, flake.nix is not quite the same as the Debian package. Flake can be thought of as a function that takes some input (other directories, repositories that also contain flake.nix files), locks those input versions so that the output can be cached (flake.lock), and gives reproducible output (binary in this particular situation). Since this repository will also be used by the end user as an input, it will be necessary to fix the version of the repo by commit hash, and the flake itself (since it's the thing that's being cached) will need to have access to the source code, so it must sit at the root of repository.

Flake is not a thing used only for packaging, for example besides packaging skippy-xd it may be possible to define some auto-formatting workflow with dependencies like clang-format (or any other code formatters/linters), and then execute their cached versions (since dependencies i.e. function/flake argument versions are fixed in flake.lock) on github action to reformat code.

If you're interested, I may create such a github action workflow with other PR, which will format the code on trunk merges based on Microsoft or Linux kernel style guidelines, if it'll make your development of this useful software a bit easier.

**Comment by felixfung** [comment]
Stupid quesion from me: why can't we simply update https://github.com/NixOS/nixpkgs/blob/3d06f73179401bcce967c5a5b54cc7005cb26348/pkgs/tools/X11/skippy-xd/default.nix?

P.S. NixOS looks very interesting :)

**Comment by Lenivaya** [comment]
> Stupid quesion from me: why can't we simply update [NixOS/nixpkgs@`3d06f73`/pkgs/tools/X11/skippy-xd/default.nix](https://github.com/NixOS/nixpkgs/blob/3d06f73179401bcce967c5a5b54cc7005cb26348/pkgs/tools/X11/skippy-xd/default.nix)?

I'll definitely create a PR in nixpkgs with proposal of migration to your fork as one being actively developed, but a bit later. Flake is different from updating package in nixpkgs, because it gives user a way to "self-maintain" a version of a package without really knowing what's going on in nixpkgs (he doesn't need to create PR if he just wants to update to the latest version, he doesn't need to wait for the update availability if it has been merged but is currently floating between unstable and stable channels, he doesn't need to update his nixpkgs input etc).

For example consider some user having such a piece of system configuration he uses:

```nix
nixpkgs.url = "nixpkgs/nixos-unstable";
skippy-xd = {
  url = "github:felixfung/skippy-xd";
  inputs.nixpkgs.follows = "nixpkgs";
};

```

```nix
{inputs, ...}: {nixpkgs.overlays = [inputs.skippy-xd.overlays.default];}
```

If he suddenly wants to update skippy-xd to latest version he will just run this update over only one input:
```shell
nix flake lock --update-input skippy-xd
```

Voilà! Now the system will build with the latest version of skippy, with no changes to the skippy repo, no changes to the nixpkgs repo, just this input updated on the user side.

**Comment by Lenivaya** [comment]
In any case, I also updated the version used in nixpkgs with nixos/nixpkgs#307305

**Comment by felixfung** [comment]
I messed up the git history, that's what pushed so many commits....

I'll focus on fixing that before I can review your pr

**Comment by felixfung** [comment]
Hi @Lenivaya I thought about it a bit. I guess I don't understand Nix enough to feel comfortable with this. I guess NixOS/nixpkgs@3d06f73/pkgs/tools/X11/skippy-xd/default.nix together with your fork would suffix?

**Pull request closed without merging**
